### ISSUE TITLE
pattern to pytest-parametrize on event

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/ops-scenario#189]
with scenario 6, I was used to:

```python
@pytest.mark.parametrize("event_name", ("update_status", "start", "install"))
def test_foo(ctx, state, event_name):
    state_out = ctx.run(event_name, state)
```

With scenario 7, short of ugly-ish hacks such as

```python
@pytest.mark.parametrize("event_name", ("update_status", "start", "install"))
def test_foo(ctx, state, event_name):
    state_out = ctx.run(getattr(ctx.on, event_name)(), state)
```

there is no way to do that.
Do we want to discourage this pattern altogether, put our lawful-good hat on and hit the 'one-test-one-event' button, or do we want to support this? What's the recommended Scenario 7 equivalent?

**Comment by benhoyt** [comment]
I think the `getattr` is pretty natural, actually, though I'd probably split it onto two lines for clarity/simplicity:

```python
@pytest.mark.parametrize("event_name", ("update_status", "start", "install"))
def test_foo(ctx, state, event_name):
    event_func = getattr(ctx.on, event_name)
    state_out = ctx.run(event_func(), state)
```

(I think) you could also do:

```python
@pytest.mark.parametrize("event", [
    Context.on.update_status(),
    Context.on.start(),
    Context.on.install(),
])
def test_foo(ctx, state, event):
    ctx.run(event(), state)
```

**Comment by tonyandrewmeyer** [comment]
I think it's fine to have a parametrised test that takes an event as one of the params. It's still one-test-one-event, imo.

> (I think) you could also do:
> 
> ```python
> @pytest.mark.parametrize("event", [
>     Context.on.update_status(),
>     Context.on.start(),
>     Context.on.install(),
> ])
> def test_foo(ctx, state, event):
>     ctx.run(event(), state)
> ```

Not currently (ignoring the accidental double call). `on` is only set in `__init__` - the type and doc is defined at the class level, but there's no value until you get an instance of `Context`. It would be trivial to change, if we did want this to work. I'm prefer not to, so that people don't start doing, e.g., `ctx.run(Context.on.start(), state)`.

You could do essentially the same with `CharmEvents`:

```python
@pytest.mark.parametrize("event", [
    CharmEvents.update_status,
    CharmEvents.start,
    CharmEvents.install,
])
def test_foo(ctx, state, event):
    ctx.run(event(), state)
```

I also think the `getattr` looks fine, for what it's worth. I think it's my preferred style out of the three, although I don't mind the `CharmEvents` one.
